### PR TITLE
HuggingFace Inference SUT

### PR DESCRIPTION
**Pull request by bkorycki**

### CODE REVIEW

**Review by wpietri — APPROVED** [review]
Long term I'd like to see much of the HuggingFace shenanigans pulled out elsewhere, but this is fine for now.

**Comment by bkorycki** [comment]
@wpietri Like what specifically? The code all seems specific to huggingface to me.

**Review by rogthefrog — APPROVED** [review]
👍🏻 

A few thoughts about how to address the together/huggingface/other client management in [this comment](https://github.com/mlcommons/modelgauge/pull/560#issuecomment-2342405136).

**Comment by wpietri** [comment]
> @wpietri Like what specifically? The code all seems specific to huggingface to me.

That's exactly my concern. There's a lot about Hugging Face that's not particularly about a SUT. Since we have annotators that also deal with HuggingFace, there's duplication to be extracted. I also think the stuff about waiting to spin up a model is very much not about SUT-ness, and more about operational concerns.

**Pull request merged**
