### PR TITLE
First draft of a high level design philosophy doc.

### PR DESCRIPTION
**Pull request by brianwgoldman**

### CODE REVIEW

**Review by wpietri — APPROVED** [review]
Great start as is, and I'm fine with merging it. But I'm left hungry for examples. Could you scatter more examples throughout? Or might it makes sense to just describe the high-level architecture and mention how some of these points apply?

**Comment by brianwgoldman** [comment]
> Could you scatter more examples throughout?

I added an `Examples in practice` subsection to each section. PTAL.

**Comment by bkorycki** [comment]
LGTM!

**Review by bkorycki — APPROVED** [review]

**Review by wpietri — APPROVED** [review]
Looks great! The added examples definitely help.

**Review by bollacker — APPROVED** [review]
This is nice.

**Review by mkly — APPROVED** [review]

**Pull request merged**
